don't use obsolete/deprecated/unavailable symbols as the main symbol
swiftlang/swift-docc-symbolkit pull request #91
Opened 2024-12-17 23:14 UTC by QuietMisdreavus

Bug/issue #, if applicable: rdar://138648876

## Summary

In rare scenarios, it's possible for an Objective-C symbol to be imported into Swift with two names: One with a direct translation of the parameter names, and one with a modified symbol name. The former is imported with an obsolete availability marker, with a `renamed` key that points to the latter. SymbolKit's current selection behavior for symbol alternates chooses the original name, since the declaration is longer than the modified version. This leads to an obsolete symbol being represented in the decoded symbol graph, even though there is a non-obsolete declaration available for that symbol.

This PR updates the alternate symbol selection to prefer symbols that are not obsolete, deprecated, or unavailable.

## Dependencies

None

## Testing

Unfortunately, i could not reproduce the scenario in a test project, so i can only assume there is a special-case somewhere for Apple's SDKs. The test data included in this PR is derived from the original issue.

The obsolete-alternate scenario can be observed by generating symbol graphs for Apple's UIKit framework:

```
xcrun swift-symbolgraph-extract -sdk "$(xcrun --sdk iphoneos --show-sdk-path)" -module-name UIKit -output-dir /path/to/symbols
```

Searching for symbols with a precise identifier matching the test data from this PR will reveal the symbol in question.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ n/a ] Updated documentation if necessary

2024-12-17 23:14 UTC, QuietMisdreavus commented
@swift-ci Please test

2024-12-18 14:28 UTC, d-ronnqvist commented on Tests/SymbolKitTests/SymbolGraph/SymbolGraphTests.swift
> +      "spelling" : "init(named:inBundle:compatibleWithTraitCollection:)"
I don't think we should include real symbol names or identifiers from any real project in the repo as test data, no matter what that project is.

This data is already manipulated to be minimized (the real symbol would have many different declaration fragments of different kinds). I don't see a reason not to also change the `identifier.precise`, `pathComponents`, `names.title`, `declarationFragments[0].spelling`, and `availability[0].renamed` to use made up values (and make the corresponding changes to the other symbol).

2024-12-18 14:29 UTC, d-ronnqvist requested changes
The code looks good but I would like us to change the test data before merging this.

2024-12-18 16:25 UTC, QuietMisdreavus commented
@swift-ci Please test

2024-12-18 16:28 UTC, d-ronnqvist approved these changes

2024-12-18 16:33 UTC, merged